openfoodfact: 
  apiurl: https://fr.openfoodfacts.org/api/v0/produit/
  nutriments: 
    attr: nutriments
    listnutritionnegative: 
      - energy_points
      - saturated_fat_ratio_points
      - sodium_points
      - sugars_points
    listnutritionpositive : 
      - fiber_points
      - proteins_points
server.port: 8081
